version: "3.9"
   
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_CONNSTRING=${PG_CONNSTRING}
      - POSTGRES_NAME=products
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    restart: on-failure
    depends_on:
      - db